### ISSUE TITLE
Could you provide binaries?

### ISSUE THREAD

**Issue by Eiyeron** [Vogtinator/ConvertImg#4]
Hi.

I have no way to compile CIMG on my computer for windows (to directly compile things for it) as Qt won't work. So basically, I can't do any progress on some projects. COuld you provide (at least) Windows binaries for people to get on the program for the last version, please?

Thanks in advance.

Regards.

**Comment by adriweb** [comment]
Does this work? Just built with Qt 5.6 Win32 MinGW (and with an unofficial minimal icu DLL...)

[ConvertImg-win32.zip](https://github.com/Vogtinator/ConvertImg/files/93904/ConvertImg-win32.zip)

**Comment by Eiyeron** [comment]
Hi. Yes, it worked without issues. Thanks for your work.
